# Generated by Django 4.2.7 on 2023-11-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earthquakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField()),
                ('time', models.CharField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('depth', models.IntegerField()),
                ('magnitude', models.FloatField()),
            ],
        ),
    ]
